targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: grapql_serializer|lib/graphql-schema/schema/schema.graphql
          when_extensions:
            when: true
            maybeWhen: true
          type_overrides:
            JSON:
              name: BuiltMap<String, dynamic>
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: grapql_serializer|lib/graphql-schema/schema/schema.graphql
          when_extensions:
            when: true
            maybeWhen: true
          custom_serializers:
            - import: 'package:grapql_serializer/metadata_serializer.dart'
              name: GenericScalarSerializer
          type_overrides:
            JSON:
              name: BuiltMap<String, dynamic>
#targets:
#  $default:
#    builders:
#      gql_build|schema_builder:
#        enabled: true
#        options:
#          type_overrides:
#            JSON:
#              name: JsonObject
#              import: "package:built_value/json_object.dart"
#      gql_build|ast_builder:
#        enabled: true
#      gql_build|data_builder:
#        enabled: true
#        options:
#          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
#          type_overrides:
#            JSON:
#              name: JsonObject
#              import: "package:built_value/json_object.dart"
#      gql_build|var_builder:
#        enabled: true
#        options:
#          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
#          type_overrides:
#            JSON:
#              name: JsonObject
#              import: "package:built_value/json_object.dart"
#      gql_build|serializer_builder:
#        enabled: true
#        options:
#          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
#          custom_serializers:
#            - import: "package:built_value/src/json_object_serializer.dart"
#              name: JsonObjectSerializer
#
#      ferry_generator|req_builder:
#        enabled: true
#        options:
#          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
#          type_overrides:
#            JSON:
#              name: JsonObject
#              import: "package:built_value/json_object.dart"

#targets:
#  $default:
#    builders:
#      gql_build|schema_builder:
#        enabled: true
#        options:
#          type_overrides:
#            JSON:
#              name: Map<String, dynamic>
#      gql_build|ast_builder:
#        enabled: true
#
#      gql_build|data_builder:
#        enabled: true
#        options:
#          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
#          type_overrides:
#            JSON:
#              name: Map<String, dynamic>
#      gql_build|var_builder:
#        enabled: true
#        options:
#          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
#          type_overrides:
#            JSON:
#              name: Map<String, dynamic>
#      gql_build|serializer_builder:
#        enabled: true
#        options:
#          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
#          custom_serializers:
#            - import: 'package:metadata_serializer.dart'
#              name: MetadataSerializer
#
#      ferry_generator|req_builder:
#        enabled: true
#        options:
#          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
#          type_overrides:
#            JSON:
#              name: Map<String, dynamic>
